import { useRef } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { Canvas } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

// Auto generated by https://github.com/pmndrs/gltfjsx
// And modified by me :)
function Model(props) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/models/icon/NowLiveIcon.gltf');
	return (
		<group ref={group} {...props} dispose={null}>
			<group
				position={[-1.52, -1.54, 0]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={13.3}
			>
				<mesh
					geometry={nodes.Curve002_1.geometry}
					material={materials['Twitch Purple']}
				/>
				<mesh
					geometry={nodes.Curve002_2.geometry}
					material={materials['White.001']}
				/>
				<mesh
					geometry={nodes.Curve002_3.geometry}
					material={materials['Rec Icon']}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/models/icon/NowLiveIcon.gltf');

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Coming Soon!</title>
				<meta
					name='description'
					content='Website for the Now Live chrome extension'
				/>
			</Head>

			<main className={styles.main}>
				<h1>Welcome to Now Live!</h1>
				<Canvas>
					<ambientLight />
					<pointLight position={[10, 10, 10]} />
					<Model position={[0, 0, 0]} />
				</Canvas>
			</main>

			<footer className={styles.footer}>
				<p>
					Developed by{' '}
					<a
						href='https://github.com/jamesinaxx'
						className={styles.userLink}
					>
						jamesinaxx
					</a>
				</p>
			</footer>
		</div>
	);
}
